name: Release CD

on:
  workflow_dispatch :
  release:
    types: [created]

jobs:
  build:
    name: Build and Publish Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20
      - name: Set GOPATH
        run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        
      - name: Get dependencies
        run: go get -v -t -d ./...
        
      - name: Compile Go code
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/belfast-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: belfast-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/belfast-${{ matrix.goos }}-${{ matrix.goarch }}

  publish:
    name: Publish Release Assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: belfast-linux-amd64
          path: build/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: belfast-windows-amd64
          path: build/

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: belfast-darwin-amd64
          path: build/

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            build/belfast-linux-amd64
            build/belfast-windows-amd64.exe
            build/belfast-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
